---
title: "Homework 4"
author: "Benjamin Noland"
output: pdf_document
fontsize: 12pt
---

```{r setup, include = FALSE}
library(TSA)

knitr::opts_chunk$set(
  echo = TRUE,
  fig.width = 6,
  fig.asp = 0.618,
  out.width = "70%",
  fig.align = "center",
  fig.show = "hold"
)
```

\newcommand{\var}{\mathrm{Var}}
\newcommand{\cov}{\mathrm{Cov}}
\newcommand{\corr}{\mathrm{Corr}}
\newcommand{\E}{\mathrm{E}}
\newcommand{\pr}{\mathrm{P}}

1. (Cryer & Chan, Exercise 4.11) The process $\{Y_t\}$ is of the form $$Y_t =
\phi Y_{t-1} + e_t - \theta_1 e_{t-1} - \theta_2 e_{t-2},$$ with $\phi = 0.8$,
$\theta_1 = -0.7$, and $\theta_2 = -0.6$. In particular, note that the process
has AR characteristic polynomial $\phi(x) = 1 - 0.8x$, which has the single root
$x = 1.25 > 1$. Thus the process is stationary.

    First, we compute
    $$\E(e_t Y_t)
      = \E[e_t (\phi Y_{t-1} + e_t - \theta_1 e_{t-1} - \theta_2 e_{t-2})]
      = \E(e_t^2)
      = \sigma_e^2.$$
    Next, we have
    $$\begin{aligned}
    \E(e_{t-1} Y_t)
      &= \E[e_{t-1} (\phi Y_{t-1} + e_t - \theta_1 e_{t-1} - \theta_2 e_{t-2})] \\
      &= \phi \E(e_{t-1} Y_{t-1}) - \theta_1 \E(e_{t-1}^2) \\
      &= \phi \sigma_e^2 - \theta_1 \sigma_e^2 \\
      &= (\phi - \theta_1) \sigma_e^2.
    \end{aligned}$$
    Finally,
    $$\begin{aligned}
      \E(e_{t-2} Y_t)
        &= \E[e_{t-2} (\phi Y_{t-1} + e_t - \theta_1 e_{t-1} - \theta_2 e_{t-2})] \\
        &= \phi \E(e_{t-2} Y_{t-1}) - \theta_2 \E(e_{t-2}^2) \\
        &= \phi (\phi - \theta_1) \sigma_e^2 - \theta_2 \sigma_e^2 \\
        &= [\phi (\phi - \theta_1) - \theta_2] \sigma_e^2.
    \end{aligned}$$
    Thus we can write the autocovariance function as
    $$\begin{aligned}
      \gamma_k &= \cov(Y_t, Y_{t-k}) \\
        &= \E[Y_{t-k} (\phi Y_{t-1} + e_t - \theta_1 e_{t-1} - \theta_2 e_{t-2})] \\
        &= \phi \E(Y_{t-k} Y_{t-1}) + \E(Y_{t-k} e_t)
          - \theta_1 \E(Y_{t-k} e_{t-1}) - \theta_2 \E(Y_{t-k} e_{t-2}) \\
        &= \phi \gamma_{k-1} + \E(Y_{t-k} e_t)
          - \theta_1 \E(Y_{t-k} e_{t-1}) - \theta_2 \E(Y_{t-k} e_{t-2})
    \end{aligned}$$
    for any time $t$ and lag $k$.
    
    a. Let $k > 2$. Then the expression for $\gamma_k$ above immediately gives
    us
    $$\gamma_k = \phi \gamma_{k-1},$$
    so that
    $$\rho_k = \frac{\gamma_k}{\gamma_0} = \phi \rho_{k-1} = 0.8 \rho_{k-1}.$$
    
    b. Again, using the expressions computed above, we get
    $$\gamma_2 = \phi \gamma_1 - \theta_2 \E(Y_{t-2} e_{t-2})
      = \phi \gamma_1 - \theta_2 \sigma_e^2,$$
    so that
    $$\phi_2 = \frac{\gamma_2}{\gamma_0}
      = \phi \rho_1 - \frac{\theta_2 \sigma_e^2}{\gamma_0}
      = 0.8 \rho_1 + \frac{0.6 \sigma_e^2}{\gamma_0}.$$

2. (Cryer & Chan, Exercise 4.12)
    a. Note that in general, an MA(2) process with parameters $\theta_1$ and
    $\theta_2$ has autocorrelation function $\rho_k$ given by
    $$\begin{aligned}
      \rho_1 &= \frac{-\theta_1 + \theta_1 \theta_2}
        {1 + \theta_1^2 + \theta_2^2} \\
      \rho_2 &= \frac{-\theta_2}{1 + \theta_1^2 + \theta_2^2} \\
      \rho_k &= 0 \quad \text{for every $k > 2$}.
    \end{aligned}$$
    Thus we find that for both of the processes in question, $\rho_1 = -5/38$,
    $\rho_2 = -3/19$, and $\rho_k = 0$ for every $k > 2$. The two processes
    therefore have the same autocorrelation structure.
    
    b. The process with $\theta_1 = \theta_2 = 1/6$ has MA characteristic
    polynomial $\theta(x) = 1 - (1/6)x - (1/6)x^2$, which has roots $x = -3, 2$.
    So this process is invertible. On the other hand, the process with $\theta_1
    = -1$ and $\theta_2 = 6$ has MA characteristic polynomial
    $\theta(x) = 1 + x - 6x^2$, which has roots $x = -1/3, 1/2$, and so this
    second process is \emph{not} invertible.
    
        This is an example of the following result: there is only one set of
        parameter values $\theta_1, \ldots, \theta_q$ that yield an invertible
        MA($q$) process with a given autocorrelation function.

3. (Cryer & Chan, Exercise 4.21)
4.
5. (Cryer & Chan, Exercise 5.1)
6. (Cryer & Chan, Exercise 5.4)
